export default {
   gainers: [
      {
         netChange: 3.11,
         volume: 18409125,
         ticker: "CBAY",
         performanceID: "0P00011RLM",
         name: "CymaBay Therapeutics",
         exchange: "XNAS",
         percentNetChange: 39.6684,
         lastPrice: 10.95,
      },
      {
         netChange: 1.59,
         volume: 42386500,
         ticker: "XPEV",
         performanceID: "0P0001KL0F",
         name: "XPeng",
         exchange: "XNYS",
         percentNetChange: 13.4404,
         lastPrice: 13.42,
      },
      {
         netChange: 0.84,
         volume: 625677,
         ticker: "ALVO",
         performanceID: "0P0001P7TI",
         name: "Alvotech",
         exchange: "XNAS",
         percentNetChange: 12.1739,
         lastPrice: 7.74,
      },
      {
         netChange: 1.95,
         volume: 167862,
         ticker: "TYGO",
         performanceID: "0P0001QT0F",
         name: "Tigo Energy",
         exchange: "XNAS",
         percentNetChange: 11.747,
         lastPrice: 18.55,
      },
      {
         netChange: 1.64,
         volume: 1909925,
         ticker: "AVDL",
         performanceID: "0P00000287",
         name: "Avadel Pharmaceuticals plc",
         exchange: "XNAS",
         percentNetChange: 11.0512,
         lastPrice: 16.48,
      },
      {
         netChange: 5.1,
         volume: 1671194,
         ticker: "TDW",
         performanceID: "0P0001BFE0",
         name: "Tidewater",
         exchange: "XNYS",
         percentNetChange: 10.1311,
         lastPrice: 55.44,
      },
      {
         netChange: 0.44,
         volume: 412896,
         ticker: "DOMA",
         performanceID: "0P0001N13X",
         name: "Doma Holdings",
         exchange: "XNYS",
         percentNetChange: 9.7778,
         lastPrice: 4.94,
      },
      {
         netChange: 1.67,
         volume: 115111241,
         ticker: "CCL",
         performanceID: "0P0000013F",
         name: "Carnival Corp",
         exchange: "XNYS",
         percentNetChange: 9.7319,
         lastPrice: 18.83,
      },
      {
         netChange: 0.59,
         volume: 34360223,
         ticker: "RIG",
         performanceID: "0P000005I4",
         name: "Transocean Ltd",
         exchange: "XNYS",
         percentNetChange: 9.19,
         lastPrice: 7.01,
      },
      {
         netChange: 1.41,
         volume: 5403114,
         ticker: "CUK",
         performanceID: "0P0000013G",
         name: "Carnival PLC",
         exchange: "XNYS",
         percentNetChange: 9.0734,
         lastPrice: 16.95,
      },
   ],
   actives: [
      {
         netChange: 1.67,
         volume: 115111241,
         ticker: "CCL",
         performanceID: "0P0000013F",
         name: "Carnival Corp",
         exchange: "XNYS",
         percentNetChange: 9.7319,
         lastPrice: 18.83,
      },
      {
         netChange: 4.27,
         volume: 112620784,
         ticker: "TSLA",
         performanceID: "0P0000OQN8",
         name: "Tesla",
         exchange: "XNAS",
         percentNetChange: 1.6583,
         lastPrice: 261.77,
      },
      {
         netChange: -0.37,
         volume: 98384634,
         ticker: "SOFI",
         performanceID: "0P0001MMYT",
         name: "SoFi Technologies",
         exchange: "XNAS",
         percentNetChange: -4.248,
         lastPrice: 8.34,
      },
      {
         netChange: 4.38,
         volume: 85213216,
         ticker: "AAPL",
         performanceID: "0P000000GY",
         name: "Apple",
         exchange: "XNAS",
         percentNetChange: 2.3102,
         lastPrice: 193.97,
      },
      {
         netChange: 0.01,
         volume: 73348891,
         ticker: "LCID",
         performanceID: "0P0001N05O",
         name: "Lucid Group",
         exchange: "XNAS",
         percentNetChange: 0.1453,
         lastPrice: 6.89,
      },
      {
         netChange: 0.04,
         volume: 63953206,
         ticker: "MARA",
         performanceID: "0P0000STDD",
         name: "Marathon Digital Holdings",
         exchange: "XNAS",
         percentNetChange: 0.2894,
         lastPrice: 13.86,
      },
      {
         netChange: 0.3,
         volume: 63465222,
         ticker: "NIO",
         performanceID: "0P0001EEPZ",
         name: "NIO Inc.",
         exchange: "XNYS",
         percentNetChange: 3.1949,
         lastPrice: 9.69,
      },
      {
         netChange: 2.46,
         volume: 54350684,
         ticker: "AMZN",
         performanceID: "0P000000B7",
         name: "Amazon.com",
         exchange: "XNAS",
         percentNetChange: 1.9234,
         lastPrice: 130.36,
      },
      {
         netChange: 0.18,
         volume: 54036917,
         ticker: "F",
         performanceID: "0P0000029A",
         name: "Ford Motor Company",
         exchange: "XNYS",
         percentNetChange: 1.204,
         lastPrice: 15.13,
      },
      {
         netChange: 2.67,
         volume: 53378774,
         ticker: "AMD",
         performanceID: "0P0000006A",
         name: "Advanced Micro Devices",
         exchange: "XNAS",
         percentNetChange: 2.4002,
         lastPrice: 113.91,
      },
   ],
   losers: [
      {
         netChange: -0.35,
         volume: 51836068,
         ticker: "SPCE",
         performanceID: "0P0001BP51",
         name: "Virgin Galactic Holdings",
         exchange: "XNYS",
         percentNetChange: -8.2742,
         lastPrice: 3.88,
      },
      {
         netChange: -0.96,
         volume: 943849,
         ticker: "HPK",
         performanceID: "0P0001KL2V",
         name: "HighPeak Energy",
         exchange: "XNAS",
         percentNetChange: -8.1081,
         lastPrice: 10.88,
      },
      {
         netChange: -0.95,
         volume: 336323,
         ticker: "IE",
         performanceID: "0P0001PAAI",
         name: "Ivanhoe Electric",
         exchange: "XNYS",
         percentNetChange: -6.7906,
         lastPrice: 13.04,
      },
      {
         netChange: -0.83,
         volume: 3293511,
         ticker: "RDFN",
         performanceID: "0P0001BCS1",
         name: "Redfin Corp",
         exchange: "XNAS",
         percentNetChange: -6.2642,
         lastPrice: 12.42,
      },
      {
         netChange: -0.81,
         volume: 983731,
         ticker: "CRCT",
         performanceID: "0P0001LXZY",
         name: "Cricut",
         exchange: "XNAS",
         percentNetChange: -6.226,
         lastPrice: 12.2,
      },
      {
         netChange: -2.58,
         volume: 1947364,
         ticker: "CAVA",
         performanceID: "0P0001R1Z8",
         name: "CAVA Group",
         exchange: "XNYS",
         percentNetChange: -5.9269,
         lastPrice: 40.95,
      },
      {
         netChange: -0.68,
         volume: 39066,
         ticker: "BTDR",
         performanceID: "0P0001QTHE",
         name: "Bitdeer Technologies Group",
         exchange: "XNAS",
         percentNetChange: -5.7239,
         lastPrice: 11.2,
      },
      {
         netChange: -1.3,
         volume: 486891,
         ticker: "ARVN",
         performanceID: "0P0001EKCY",
         name: "Arvinas",
         exchange: "XNAS",
         percentNetChange: -4.977,
         lastPrice: 24.82,
      },
      {
         netChange: -3.17,
         volume: 725799,
         ticker: "BPMC",
         performanceID: "0P00015V5E",
         name: "Blueprint Medicines Corp",
         exchange: "XNAS",
         percentNetChange: -4.7763,
         lastPrice: 63.2,
      },
      {
         netChange: -1.61,
         volume: 528454,
         ticker: "MSGE",
         performanceID: "0P0001QRYL",
         name: "Madison Square Garden Entertainment Corp",
         exchange: "XNYS",
         percentNetChange: -4.57,
         lastPrice: 33.62,
      },
   ],
};
