import "./globals.css";
import { Recursive } from "next/font/google";
// import Navbar from "@/components/Navbar";
import MobileNavbar from "@/components/MobileNavbar";
import Navbar from "@/components/Navbar";
import { StockProvider } from "@/context/StockContext";
import IndexesProvider from "@/context/IndexesContext";
// import NavbarContainer from "@/components/NavbarContainer";

const inter = Recursive({ subsets: ["latin"] });

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <div className="flex">
               <Navbar />
               <MobileNavbar />
               <IndexesProvider>
                  <StockProvider>{children}</StockProvider>
               </IndexesProvider>
            </div>
         </body>
      </html>
   );
}
