const cryptos = [
   "BTC Bitcoin",
   "ETH Ethereum",
   "BNB Binance Coin",
   "ADA Cardano",
   "XRP Ripple",
   "DOGE Dogecoin",
   "LTC Litecoin",
   "BCH Bitcoin Cash",
   "DOT Polkadot",
   "LINK Chainlink",
   "XLM Stellar",
   "USDT Tether",
   "UNI Uniswap",
   "THETA Theta Token",
   "XEM NEM",
   "VET VeChain",
   "EOS EOS",
   "AAVE Aave",
   "TRX TRON",
   "XTZ Tezos",
   "SOL Solana",
   "FIL Filecoin",
   "XMR Monero",
   "ATOM Cosmos",
   "MIOTA IOTA",
   "NEO NEO",
   "DASH Dash",
   "MKR Maker",
   "COMP Compound",
   "FTT FTX Token",
   "LUNA Terra",
   "YFI yearn.finance",
   "UMA UMA",
   "SUSHI SushiSwap",
   "ZEC Zcash",
   "KSM Kusama",
   "ALGO Algorand",
   "REN Ren",
   "SNX Synthetix",
   "NEAR Near Protocol",
   "HT Huobi Token",
   "ENJ Enjin Coin",
   "CHZ Chiliz",
   "BAT Basic Attention Token",
   "RUNE THORChain",
   "MANA Decentraland",
   "HOT Holo",
   "ZIL Zilliqa",
   "CRV Curve DAO Token",
   "GRT The Graph",
   "CELO Celo",
   "RVN Ravencoin",
   "OKB OKB",
   "ICX ICON",
   "STMX StormX",
   "FTM Fantom",
   "DGB DigiByte",
   "LRC Loopring",
   "BTT BitTorrent",
   "XVG Verge",
   "HNT Helium",
   "DODO DODO",
   "CTSI Cartesi",
   "BTMX BitMax Token",
   "IOST IOST",
   "SAND The Sandbox",
   "XDC XinFin Network",
   "OCEAN Ocean Protocol",
   "NEXO Nexo",
   "CRV Curve",
   "KNC Kyber Network",
   "SRM Serum",
   "ONE Harmony",
   "OMG OMG Network",
   "TWT Trust Wallet Token",
   "CVC Civic",
   "BAL Balancer",
   "GLM Golem",
   "GNO Gnosis",
   "BAND Band Protocol",
   "RLC iExec RLC",
   "HUSD HUSD",
   "SXP Swipe",
   "STPT STP Network",
   "WAXP WAX",
   "GNT Golem",
   "ANT Aragon",
   "BNT Bancor",
   "BTS BitShares",
   "REP Augur",
   "CRV Curve DAO Token",
   "EGLD Elrond",
   "CRO Crypto.com Coin",
   "AMP Amp",
   "UTK Utrust",
   "FET Fetch.ai",
   "ARDR Ardor",
   "YFII yearn.finance",
   "AKRO Akropolis",
   "ADX AdEx",
   "ZEN Horizen",
];

import { NextResponse } from "next/server";

export async function GET() {
   return NextResponse.json(cryptos);
}
