const juicyStocks = [
   "AAPL Apple",
   "TSLA Tesla",
   "AMZN Amazon",
   "GOOGL Alphabet",
   "MSFT Microsoft",
   "META Facebook",
   "NVDA NVIDIA",
   "JPM JPMorgan Chase",
   "V Visa",
   "MA Mastercard",
   "JNJ Johnson & Johnson",
   "BABA Alibaba Group",
   "WMT Walmart",
   "BRK.A Berkshire Hathaway",
   "PG Procter & Gamble",
   "UNH UnitedHealth Group",
   "VZ Verizon Communications",
   "NFLX Netflix",
   "DIS Disney",
   "PYPL PayPal Holdings",
   "CRM Salesforce",
   "ADBE Adobe",
   "CSCO Cisco Systems",
   "INTC Intel",
   "CMCSA Comcast",
   "PEP PepsiCo",
   "ABT Abbott Laboratories",
   "ABBV AbbVie",
   "T AT&T",
   "MCD McDonald's",
   "KO The Coca-Cola Company",
   "XOM Exxon Mobil",
   "CVX Chevron",
   "BAC Bank of America",
   "NKE Nike",
   "TSM Taiwan Semiconductor Manufacturing Company",
   "ORCL Oracle",
   "PM Philip Morris International",
   "HD The Home Depot",
   "PFE Pfizer",
   "NVS Novartis",
   "MRK Merck",
   "UPS United Parcel Service",
   "COST Costco Wholesale",
   "BA Boeing",
   "WFC Wells Fargo",
   "IBM IBM",
   "PEP PepsiCo",
   "GS Goldman Sachs",
   "SAP SAP",
   "INTU Intuit",
   "TGT Target",
   "AAL American Airlines Group",
   "BA Boeing",
   "DAL Delta Air Lines",
   "UAL United Airlines Holdings",
   "LMT Lockheed Martin",
   "FDX FedEx",
   "TWTR Twitter",
   "UBER Uber Technologies",
   "LYFT Lyft",
   "EBAY eBay",
   "SBUX Starbucks",
   "AMD Advanced Micro Devices",
   "QCOM Qualcomm",
   "CVS CVS Health",
   "LRCX Lam Research",
   "TXN Texas Instruments",
   "ABB ABB",
   "MGM MGM Resorts International",
   "HPQ HP",
   "LOW Lowe's",
   "CAT Caterpillar",
   "WBA Walgreens Boots Alliance",
   "MS Morgan Stanley",
   "USB U.S. Bancorp",
   "BLK BlackRock",
   "BK The Bank of New York Mellon",
   "CELG Celgene",
   "APTV Aptiv",
   "GILD Gilead Sciences",
   "BMY Bristol Myers Squibb",
   "EBAY eBay",
   "GM General Motors",
   "TWLO Twilio",
   "ADP Automatic Data Processing",
   "ATVI Activision Blizzard",
   "DOW Dow Inc.",
   "CHTR Charter Communications",
   "APC Anadarko Petroleum",
   "BBY Best Buy",
   "SBAC SBA Communications",
   "MSI Motorola Solutions",
   "FOXA Fox Corporation",
];

import { NextResponse } from "next/server";

export async function GET() {
   return NextResponse.json(juicyStocks);
}
